.PHONY: clean All

All:
	@echo "----------Building project:[ N_Body_Problem - Debug ]----------"
	@cd "N_Body_Problem" && "$(MAKE)" -f  "N_Body_Problem.mk"
clean:
	@echo "----------Cleaning project:[ N_Body_Problem - Debug ]----------"
	@cd "N_Body_Problem" && "$(MAKE)" -f  "N_Body_Problem.mk" clean
