.PHONY: clean All

All:
	@echo "----------Building project:[ Simulation - Debug ]----------"
	@cd "Simulation" && "$(MAKE)" -f  "Simulation.mk"
clean:
	@echo "----------Cleaning project:[ Simulation - Debug ]----------"
	@cd "Simulation" && "$(MAKE)" -f  "Simulation.mk" clean
